# Generated by Django 3.0.5 on 2020-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20200427_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_nname',
            field=models.CharField(max_length=50),
        ),
    ]
