# Generated by Django 3.0.5 on 2020-04-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_auto_20200427_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_nname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
